name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install wasm-pack
      - run: ./build.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            pkg/shannon_entropy_wasm_bg.wasm
            pkg/entropy.js
